Add Rm module
composewell/streamly-coreutils pull request #19
Opened 2022-05-02 09:56 UTC by rnjtranjan

2022-06-09 16:52 UTC, harendra-kumar requested changes

2022-06-09 16:52 UTC, harendra-kumar commented on src/Streamly/Coreutils/Rm.hs
> +    def = Force
Defaulting to force remove?

2022-06-10 19:29 UTC, harendra-kumar requested changes

2022-06-10 19:29 UTC, harendra-kumar commented on streamly-coreutils.cabal
> +     , Streamly.Coreutils.Rm
Remove additional space.

2022-06-10 19:29 UTC, harendra-kumar commented on src/Streamly/Coreutils/Rm.hs
> +        Rm {force = On} -> removePathForcibly
BUG: This will remove directories recursively even if `recursive` is not On.

2022-07-08 03:45 UTC, rnjtranjan commented on src/Streamly/Coreutils/Rm.hs
> +    def = Force
Fixed.

2022-07-08 07:09 UTC, harendra-kumar requested changes

2022-07-08 07:09 UTC, harendra-kumar commented on src/Streamly/Coreutils/Rm.hs
> +            when notDir $ removePathForcibly path
Can not use removePathForcibly without the `nuke` options, as explained above.

Here we should do:

* Check if the file exists, if does not exist then do nothing
* If it exists then call removeFile

2022-07-08 07:09 UTC, harendra-kumar commented on src/Streamly/Coreutils/Rm.hs
> +        Rm {force = Off, recursive = On} -> removeDirectoryRecursive path
It should give an error if the target directory does not exist.

2022-07-20 07:13 UTC, rnjtranjan reviewed
looks good.

2022-07-24 14:59 UTC, rnjtranjan reviewed
looks fine.

2022-07-24 18:17 UTC, merged