Add Mv module
composewell/streamly-coreutils pull request #25
Opened 2022-05-03 07:54 UTC by rnjtranjan

2022-06-09 17:55 UTC, harendra-kumar requested changes

2022-06-09 17:55 UTC, harendra-kumar commented on src/Streamly/Coreutils/Mv.hs
> +    def = Force
This is a very bad default.

2022-06-09 17:55 UTC, harendra-kumar commented on src/Streamly/Coreutils/Mv.hs
> +force = Force
`force` should be a modifier of options i.e. `force :: Switch -> Mv -> Mv`. default should be `Off`.

2022-06-09 17:55 UTC, harendra-kumar commented on src/Streamly/Coreutils/Mv.hs
> +        Force -> renameDirectory
We cannot force move a file?

2022-06-09 17:55 UTC, harendra-kumar commented on src/Streamly/Coreutils/Mv.hs
> +        CreateOnly -> renameFile
We cannot move a directory?

2022-07-06 11:53 UTC, rnjtranjan commented on src/Streamly/Coreutils/Mv.hs
> +        CreateOnly -> renameFile
Fixed.

2022-07-06 11:53 UTC, rnjtranjan commented on src/Streamly/Coreutils/Mv.hs
> +        Force -> renameDirectory
Fixed.

2022-07-18 17:57 UTC, merged