Add touch module
composewell/streamly-coreutils pull request #55
Opened 2022-07-07 07:15 UTC by rnjtranjan

2022-07-07 08:33 UTC, rnjtranjan commented
Fixes:https://github.com/composewell/streamly-coreutils/issues/39

2022-07-07 21:27 UTC, harendra-kumar requested changes

2022-07-07 21:27 UTC, harendra-kumar commented on src/Streamly/Coreutils/Touch.hs
> +setCreateNew opt cfg = cfg {createNew = opt}
can we call it `create` instead?

2022-07-07 21:27 UTC, harendra-kumar commented on src/Streamly/Coreutils/Touch.hs
> +setDeRef opt cfg = cfg {deRef = opt}
Can we call it `followLinks` to keep it similar to other commands in this package?

2022-07-07 21:27 UTC, harendra-kumar commented on src/Streamly/Coreutils/Touch.hs
> +        unless found $ writeFile path ""
We can probably just `openFile` in WriteMode instead of using writeFile.

2022-07-08 07:31 UTC, harendra-kumar requested changes

2022-07-08 07:31 UTC, harendra-kumar commented on src/Streamly/Coreutils/Touch.hs
> +        unless found $ void $ openFile path WriteMode
Instead of discarding the result we should close the Handle gracefully, something like: `openFile path WriteMode >>= hClose`

2022-07-08 07:31 UTC, harendra-kumar commented on src/Streamly/Coreutils/Touch.hs
> +    , followLinks
Can we organize the exports as;

```
      touch

     -- * Options
    , Touch
    , create
    , followLinks
```

Also, check how haddocks look.

We need to follow this same conventions in all coreutils commands.

2022-07-24 06:27 UTC, rnjtranjan reviewed
looks fine.

2022-07-24 06:30 UTC, merged