Upgrade streamly version
composewell/streamly-coreutils pull request #83
Opened 2023-01-05 12:25 UTC by rnjtranjan

2023-01-06 04:57 UTC, harendra-kumar requested changes
Same changes needed as in streamly-examples.

2023-01-06 09:59 UTC, harendra-kumar requested changes

2023-01-06 09:59 UTC, harendra-kumar commented on src/Streamly/Coreutils/Ls.hs
> +              in Stream.concatIterateWith Concur.ahead2 mapper start
use `parConcatIterate`.

2023-01-06 09:59 UTC, harendra-kumar commented on src/Streamly/Coreutils/Uniq.hs
> +import Streamly.Internal.Data.Stream (catRights)
Why Internal? You can just remove this import and use Stream.catRights, it is available in the qualified import of Stream.

2023-01-11 13:31 UTC, rnjtranjan reviewed
looks good.

2023-01-11 13:41 UTC, merged